service: slv-adf-functions
frameworkVersion: '3'
provider:
  name: azure
  region: Australia Southeast
  runtime: python3.8
  os: linux
  prefix: app
  subscriptionId: '${file(./config.json):${opt:stage}}'
  stage: '${opt:stage}'
  useDotenv: true
  environment:
    ENVIRONMENT: '${opt:stage}'
    AZURE_TENANT_ID: ${env:AZURE_TENANT_ID}
    AZURE_CLIENT_ID: ${env:AZURE_CLIENT_ID}
    AZURE_CLIENT_SECRET: ${env:AZURE_CLIENT_SECRET}
    AZURE_DEV_SUB_ID: ${env:AZURE_DEV_SUB_ID}
    LIBCAL_CLIENT_SECRET: ${env:LIBCAL_CLIENT_SECRET}
    LIBCAL_CLIENT_ID: ${env:LIBCAL_CLIENT_ID}
    LIBCAL_URL: ${env:LIBCAL_URL}
    SQL_ADMIN_USER: ''
    SQL_ADMIN_PASSWORD: ''

plugins:
  - serverless-azure-functions
package:
  patterns:
    - '!env/**'
    - '!.env/**'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.python_packages/**'
    - '!.funcignore'
    - '!package.json'
    - '!package-lock.json'
    - '!.gitignore'
    - '!.git/**'
functions:
  libcal:
    handler: src/handlers/libcal.main
    events:
      - timer: true
        name: myTimer
        x-azure-settings:
          schedule: 0 30 7 * * * # Runs daily at 7:30AM
    name: slv-adf-functions-dev-libcal
