service: slv-adf-functions

frameworkVersion: '3'

provider:
  name: azure
  region: Australia Southeast
  runtime: python3.8
  os: linux  # linux is the only operating system available for python
  prefix: ${opt:stage}  # prefix of generated resource name
  
  subscriptionId: ${file(./config.json):${opt:stage}}
  stage: ${opt:stage}
  useDotenv: true # makes variables stored in .env available

  environment:
    ENVIRONMENT: ${opt:stage}
    AZURE_TENANT_ID: $AZURE_TENANT_ID
    AZURE_CLIENT_ID: $AZURE_CLIENT_ID
    AZURE_CLIENT_SECRET: $AZURE_CLIENT_SECRET
    AZURE_DEV_SUB_ID: $AZURE_DEV_SUB_ID
    LIBCAL_CLIENT_SECRET : $LIBCAL_CLIENT_SECRET 
    LIBCAL_CLIENT_ID : $LIBCAL_CLIENT_ID 
    LIBCAL_URL : $LIBCAL_URL 

plugins:
  - serverless-azure-functions

# you can add packaging information here
package:
  patterns:
    - '!env/**'
    - '!.env/**'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.python_packages/**'
    - '!.funcignore'
    - '!package.json'
    - '!package-lock.json'
    - '!.gitignore'
    - '!.git/**'


functions:
  timer:
    handler: src/handlers/timer.main
    events:
      - timer: true
        name: myTimer
        x-azure-settings:
          schedule: '15,45 * * * * *'

